### PR TITLE
Added keystate checks and improved performance

### PR DESCRIPTION
**Pull request by capibawa**
Screenshots should not be constantly being taken, so putting it under a keystate conditional should reduce resource usage.

Also added some more variables for easy customization.

### CODE REVIEW

**Comment by capibawa** [comment]
Added static scaling for more specific customization.

**Review by spoofjack — APPROVED** [review]

**Comment by jpxue** [comment]
I like your changes but I did not get to see them before I made a bunch of changes (completely new to github and idk how it works hehe).
Apologies, if you make a new pull request I'll make sure that I commit your changes though

**Comment by capibawa** [comment]
Sure thing.

**Comment by cristiansc1993** [comment]
please make this happen

**Pull request closed without merging**
